name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "${{ secrets.GITHUB_ACTOR }}"
          git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
          gh repo create --public --confirm --description "GitHub Pages Deployment"
          gh repo view --json nameWithOwner --template "{{.nameWithOwner}}" | xargs -I '{}' gh repo clone '{}'
          mv ./build/* ./
          git add .
          git commit -m "Auto-deploy to GitHub Pages"
          git push
